//! WGSL code generation for GPU evaluation of the field.
//!
//! The viewport sphere-traces this directly; there is no tessellation in the
//! display path at all. Meshing only happens on export.
//!
//! Parameters are currently baked in as literals, which means any edit forces a
//! shader recompile. That is fine for structural edits but will be too slow for
//! dragging a value at 60fps, so before direct manipulation lands the numeric
//! leaves need to move into a uniform buffer, leaving only topology changes to
//! trigger recompilation. The emitter is structured to make that swap local.

use crate::arena::Arena;
use crate::node::{Node, NodeId};
use std::collections::HashMap;
use std::fmt::Write as _;

const PRELUDE: &str = r"
fn sc_smin(a: f32, b: f32, k: f32) -> f32 {
    let h = clamp(0.5 + 0.5 * (b - a) / k, 0.0, 1.0);
    return mix(b, a, h) - k * h * (1.0 - h);
}

fn sc_smax(a: f32, b: f32, k: f32) -> f32 {
    return -sc_smin(-a, -b, k);
}

fn sc_qrot(q: vec4<f32>, v: vec3<f32>) -> vec3<f32> {
    return v + 2.0 * cross(q.xyz, cross(q.xyz, v) + q.w * v);
}
";

/// Emits a WGSL module exposing `fn sc_sdf(p: vec3<f32>) -> f32`.
///
/// An absent or dead root yields a field that is empty everywhere, so the
/// viewport shows nothing rather than failing to compile.
#[must_use]
pub fn generate(arena: &Arena, root: Option<NodeId>) -> String {
    // `sc_selected` is emitted even with nothing selected: the renderer's shader
    // always calls it, and one empty function is cheaper than two shader
    // variants.
    compose(arena, &[("sc_sdf", root), ("sc_selected", None)])
}

/// As [`generate`], plus a second field covering only the selected subtree.
///
/// The viewport uses it to tint whatever is selected: at a surface hit it asks
/// whether that point also lies on the selection's own surface. One extra field
/// evaluation per visible pixel, and no separate pass or picking buffer.
///
/// `sc_selected` is always emitted, returning empty space when nothing is
/// selected, so the shader never has to be regenerated with a different shape.
#[must_use]
pub fn generate_with_selection(
    arena: &Arena,
    root: Option<NodeId>,
    selected: Option<NodeId>,
) -> String {
    compose(arena, &[("sc_sdf", root), ("sc_selected", selected)])
}

/// Emits a module containing one function per requested field.
///
/// Helper functions are shared across them, so two fields referring to the same
/// extruded profile emit its polygon once.
fn compose(arena: &Arena, fields: &[(&str, Option<NodeId>)]) -> String {
    let mut e = Emitter {
        arena,
        body: String::new(),
        helpers: String::new(),
        counter: 0,
        memo: HashMap::new(),
    };

    let mut functions = String::new();
    for (name, root) in fields {
        e.body.clear();
        // Variable names are scoped to the function body being written, so the
        // memo cannot carry across; the helper counter deliberately does, to
        // keep generated function names unique.
        e.memo.clear();

        let result = match root {
            Some(id) if arena.is_alive(*id) => e.emit(*id, "p"),
            _ => {
                e.line("let d_empty = 1e30;");
                "d_empty".to_string()
            }
        };
        let _ = write!(
            functions,
            "\nfn {name}(p: vec3<f32>) -> f32 {{\n{}    return {result};\n}}\n",
            e.body
        );
    }

    format!(
        "// generated by sc-geom; do not edit\n{PRELUDE}\n{}\n{functions}",
        e.helpers
    )
}

struct Emitter<'a> {
    arena: &'a Arena,
    body: String,
    /// Standalone functions emitted alongside `sc_sdf`.
    ///
    /// An extruded profile needs a loop over an array, which cannot be expressed
    /// as a single SSA statement in the main body.
    helpers: String,
    counter: u32,
    /// Keyed by (node, point expression): a shared subtree evaluated under two
    /// different transforms is genuinely two different computations.
    memo: HashMap<(NodeId, String), String>,
}

impl Emitter<'_> {
    fn fresh(&mut self, prefix: &str) -> String {
        self.counter += 1;
        format!("{prefix}{}", self.counter)
    }

    fn line(&mut self, s: &str) {
        self.body.push_str("    ");
        self.body.push_str(s);
        self.body.push('\n');
    }

    /// Emits the distance of `id` evaluated at point expression `p`, returning
    /// the name of the variable holding it.
    fn emit(&mut self, id: NodeId, p: &str) -> String {
        let key = (id, p.to_string());
        if let Some(v) = self.memo.get(&key) {
            return v.clone();
        }

        let Some(node) = self.arena.get(id).cloned() else {
            let d = self.fresh("d");
            self.line(&format!("let {d} = 1e30;"));
            return d;
        };

        let d = match node {
            Node::Sphere { .. }
            | Node::Box { .. }
            | Node::Cylinder { .. }
            | Node::Torus { .. }
            | Node::Plane { .. } => self.emit_primitive(&node, p),
            _ => self.emit_composite(&node, p),
        };

        self.memo.insert(key, d.clone());
        d
    }

    /// Closed-form distance functions. Each is exact, not merely a bound.
    fn emit_primitive(&mut self, node: &Node, p: &str) -> String {
        match *node {
            Node::Sphere { radius } => {
                let d = self.fresh("d");
                self.line(&format!("let {d} = length({p}) - {};", f(radius)));
                d
            }

            Node::Box { half, round } => {
                let q = self.fresh("q");
                let d = self.fresh("d");
                self.line(&format!(
                    "let {q} = abs({p}) - vec3<f32>({}, {}, {});",
                    f(half.x - round),
                    f(half.y - round),
                    f(half.z - round)
                ));
                self.line(&format!(
                    "let {d} = length(max({q}, vec3<f32>(0.0))) + min(max({q}.x, max({q}.y, {q}.z)), 0.0){};",
                    minus(round)
                ));
                d
            }

            Node::Cylinder {
                radius,
                half_height,
                round,
            } => {
                let q = self.fresh("q");
                let d = self.fresh("d");
                self.line(&format!(
                    "let {q} = vec2<f32>(length({p}.xy) - {}, abs({p}.z) - {});",
                    f(radius - round),
                    f(half_height - round)
                ));
                self.line(&format!(
                    "let {d} = length(max({q}, vec2<f32>(0.0))) + min(max({q}.x, {q}.y), 0.0){};",
                    minus(round)
                ));
                d
            }

            Node::Torus { major, minor } => {
                let q = self.fresh("q");
                let d = self.fresh("d");
                self.line(&format!(
                    "let {q} = vec2<f32>(length({p}.xy) - {}, {p}.z);",
                    f(major)
                ));
                self.line(&format!("let {d} = length({q}) - {};", f(minor)));
                d
            }

            Node::Plane { normal, offset } => {
                let n = normal.normalize();
                let d = self.fresh("d");
                self.line(&format!(
                    "let {d} = dot({p}, vec3<f32>({}, {}, {})) - {};",
                    f(n.x),
                    f(n.y),
                    f(n.z),
                    f(offset)
                ));
                d
            }

            _ => unreachable!("emit_primitive called with a composite node"),
        }
    }

    /// Booleans and modifiers, which recurse into their children.
    fn emit_composite(&mut self, node: &Node, p: &str) -> String {
        match *node {
            Node::Union { a, b, smooth } => {
                let (da, db) = (self.emit(a, p), self.emit(b, p));
                self.combine("min", "sc_smin", &da, &db, smooth)
            }

            Node::Difference { a, b, smooth } => {
                let (da, db) = (self.emit(a, p), self.emit(b, p));
                let neg = self.fresh("n");
                self.line(&format!("let {neg} = -{db};"));
                self.combine("max", "sc_smax", &da, &neg, smooth)
            }

            Node::Intersection { a, b, smooth } => {
                let (da, db) = (self.emit(a, p), self.emit(b, p));
                self.combine("max", "sc_smax", &da, &db, smooth)
            }

            Node::Transform { child, xform } => self.emit_transform(child, &xform, p),

            Node::Offset { child, distance } => {
                let dc = self.emit(child, p);
                if distance == 0.0 {
                    dc
                } else {
                    let d = self.fresh("d");
                    self.line(&format!("let {d} = {dc} - {};", f(distance)));
                    d
                }
            }

            Node::Extrude {
                ref profile,
                height,
            } => {
                let name = {
                    self.counter += 1;
                    format!("sc_extrude_{}", self.counter)
                };
                self.emit_extrude_fn(&name, profile, height);
                let d = self.fresh("d");
                self.line(&format!("let {d} = {name}({p});"));
                d
            }

            Node::Shell { child, thickness } => {
                let dc = self.emit(child, p);
                let d = self.fresh("d");
                self.line(&format!("let {d} = max({dc}, -({dc} + {}));", f(thickness)));
                d
            }

            _ => unreachable!("emit_composite called with a primitive node"),
        }
    }

    /// Emits a function computing the exact distance to an extruded profile.
    ///
    /// The polygon is written as a literal array and walked at runtime. This is
    /// the reason profiles are capped in size: the cost lands in generated code.
    /// Moving the vertices into a storage buffer removes both the cap and the
    /// shader recompile on every profile edit.
    fn emit_extrude_fn(&mut self, name: &str, profile: &[glam::Vec2], height: f32) {
        let n = profile.len();
        let verts = profile
            .iter()
            .map(|v| format!("vec2<f32>({}, {})", f(v.x), f(v.y)))
            .collect::<Vec<_>>()
            .join(", ");

        let _ = write!(
            self.helpers,
            "\nfn {name}(p: vec3<f32>) -> f32 {{
    var v: array<vec2<f32>, {n}> = array<vec2<f32>, {n}>({verts});
    let q = p.xy;
    var d = dot(q - v[0], q - v[0]);
    var s = 1.0;
    for (var i = 0u; i < {n}u; i = i + 1u) {{
        let j = (i + {n}u - 1u) % {n}u;
        let e = v[j] - v[i];
        let w = q - v[i];
        let b = w - e * clamp(dot(w, e) / dot(e, e), 0.0, 1.0);
        d = min(d, dot(b, b));
        // Written as three scalars rather than a bool vector: naga rejects a
        // `vec3<bool>` constructor here.
        let c0 = q.y >= v[i].y;
        let c1 = q.y < v[j].y;
        let c2 = e.x * w.y > e.y * w.x;
        if ((c0 && c1 && c2) || (!c0 && !c1 && !c2)) {{ s = -s; }}
    }}
    let plane = s * sqrt(d);
    let slab = max(-p.z, p.z - {h});
    return min(max(plane, slab), 0.0) + length(max(vec2<f32>(plane, slab), vec2<f32>(0.0)));
}}\n",
            h = f(height)
        );
    }

    /// Peephole: a placement is usually a pure translation, and the identity
    /// parts of it are dead arithmetic inside a loop that runs on the order of
    /// a hundred times per pixel. Emit only what actually does something.
    fn emit_transform(&mut self, child: NodeId, xform: &crate::math::Transform, p: &str) -> String {
        let q = xform.rotation;
        let unit_scale = (xform.scale - 1.0).abs() < 1e-9;
        let no_rotation = q.w.abs() >= 1.0 - 1e-7;
        let no_translation = xform.translation.length_squared() < 1e-18;

        let mut expr = p.to_string();
        if !no_translation {
            expr = format!(
                "({expr} - vec3<f32>({}, {}, {}))",
                f(xform.translation.x),
                f(xform.translation.y),
                f(xform.translation.z)
            );
        }
        if !no_rotation {
            expr = format!(
                "sc_qrot(vec4<f32>({}, {}, {}, {}), {expr})",
                f(-q.x),
                f(-q.y),
                f(-q.z),
                f(q.w)
            );
        }
        if !unit_scale {
            expr = format!("({expr} * {})", f(1.0 / xform.scale));
        }

        let pn = if expr == p {
            p.to_string()
        } else {
            let v = self.fresh("p");
            self.line(&format!("let {v} = {expr};"));
            v
        };

        let dc = self.emit(child, &pn);
        if unit_scale {
            dc
        } else {
            let d = self.fresh("d");
            self.line(&format!("let {d} = {dc} * {};", f(xform.scale)));
            d
        }
    }

    /// Hard combine when the blend radius is zero, smooth otherwise. Emitting
    /// `min` directly rather than always calling the smooth helper keeps the
    /// common case free of a division and a clamp.
    fn combine(&mut self, hard: &str, soft: &str, a: &str, b: &str, k: f32) -> String {
        let d = self.fresh("d");
        if k <= 0.0 {
            self.line(&format!("let {d} = {hard}({a}, {b});"));
        } else {
            self.line(&format!("let {d} = {soft}({a}, {b}, {});", f(k)));
        }
        d
    }
}

/// Emits `" - x"`, or nothing at all when x is zero.
fn minus(v: f32) -> String {
    if v == 0.0 {
        String::new()
    } else {
        format!(" - {}", f(v))
    }
}

/// Formats a float as a WGSL literal. WGSL has no infinity literal, so clamp to
/// a magnitude that behaves like one for sphere tracing.
fn f(v: f32) -> String {
    if v.is_nan() {
        return "0.0".to_string();
    }
    if !v.is_finite() {
        return if v > 0.0 {
            "1e30".into()
        } else {
            "-1e30".into()
        };
    }
    let s = format!("{v:?}");
    if s.contains('.') || s.contains('e') {
        s
    } else {
        format!("{s}.0")
    }
}
